#!/usr/bin/env ruby

require 'optparse'
require_relative '../lib/byraft'

banner = <<-BANNER
Request AppendLog to byraft application
Usage:  client <address> <command> [options]
Option: -h --help           Print help
BANNER
OptionParser.new do |parser|
  parser.banner = banner
  parser.on("-h", "--help") do
    puts banner
    exit
  end
end.parse!

if ARGV.size < 2
  puts banner
  exit
end

address = ARGV[0]
command = ARGV[1..].join(" ")
client = Byraft::GRPC::Stub.new(address, :this_channel_is_insecure)
begin
  res = client.append_log(Byraft::GRPC::AppendLogRequest.new(command: command))
  if res.success
    puts "Success."
  elsif res.leader_id.empty? || res.leader_address.empty?
    puts "Failed to request: No leader available"
  else
    puts "Retry to leader Node##{res.leader_id}: #{res.leader_address}"
  end
rescue GRPC::Unavailable => e
  puts "Failed to request: #{e}"
end
